import requests
import pandas as pd
import hashlib


#1.读取文件
targets_and_families = pd.read_csv("targetsAndFamilies/targets_and_families_test.csv")
HumanSwissProt = targets_and_families['Human SwissProt']
TargetId = targets_and_families['Target id']
RGDName = targets_and_families['RGD name']
# print(type(str(TargetId[0])))
# print(len(TargetId))

#输出文档的格式
# >178 [organism=Human] [UniprotID=Q9NYQ6] cadherin EGF LAG seven-pass G-type receptor 1
# MAPPPPPVLPVLLLLAAAAALPAMGLRAAAWEPRVPGGTRAFALRPGCTYAVGAACTPRAPRELLDVGRDGRLAGRRRVSGAGRPLPLQVRLVARSAPTALSRRLRARTHLPGCGARARLCGTGARLCGALCFPVPGGCAAAQHSALAAPTTLPACRCPPRPRPRCPGRPICLPPGGSVRLRLLCALRRAAGAVRVGLALEAATAGTPSASPSPSPPLPPNLPEARAGPARRARRGTSGRGSLKFPMPNYQVALFENEPAGTLILQLHAHYTIEGEEERVSYYMEGLFDERSRGYFRIDSATGAVSTDSVLDRETKETHVLRVKAVDYSTPPRSATTYITVLVKDTNDHSPVFEQSEYRERVRENLEVGYEVLTIRASDRDSPINANLRYRVLGGAWDVFQLNESSGVVSTRAVLDREEAAEYQLLVEANDQGRNPGPLSATATVYIEVEDENDNYPQFSEQNYVVQVPEDVGLNTAVLRVQATDRDQGQNAAIHYSILSGNVAGQFYLHSLSGILDVINPLDFEDVQKYSLSIKAQDGGRPPLINSSGVVSVQVLDVNDNEPIFVSSPFQATVLENVPLGYPVVHIQAVDADSGENARLHYRLVDTASTFLGGGSAGPKNPAPTPDFPFQIHNSSGWITVCAELDREEVEHYSFGVEAVDHGSPPMSSSTSVSITVLDVNDNDPVFTQPTYELRLNEDAAVGSSVLTLQARDRDANSVITYQLTGGNTRNRFALSSQRGGGLITLALPLDYKQEQQYVLAVTASDGTRSHTAHVLINVTDANTHRPVFQSSHYTVSVSEDRPVGTSIATLSANDEDTGENARITYVIQDPVPQFRIDPDSGTMYTMMELDYENQVAYTLTIMAQDNGIPQKSDTTTLEILILDANDNAPQFLWDFYQGSIFEDAPPSTSILQVSATDRDSGPNGRLLYTFQGGDDGDGDFYIEPTSGVIRTQRRLDRENVAVYNLWALAVDRGSPTPLSASVEIQVTILDINDNAPMFEKDELELFVEENNPVGSVVAKIRANDPDEGPNAQIMYQIVEGDMRHFFQLDLLNGDLRAMVELDFEVRREYVLVVQATSAPLVSRATVHILLVDQNDNPPVLPDFQILFNNYVTNKSNSFPTGVIGCIPAHDPDVSDSLNYTFVQGNELRLLLLDPATGELQLSRDLDNNRPLEALMEVSVSDGIHSVTAFCTLRVTIITDDMLTNSITVRLENMSQEKFLSPLLALFVEGVAAVLSTTKDDVFVFNVQNDTDVSSNILNVTFSALLPGGVRGQFFPSEDLQEQIYLNRTLLTTISTQRVLPFDDNICLREPCENYMKCVSVLRFDSSAPFLSSTTVLFRPIHPINGLRCRCPPGFTGDYCETEIDLCYSDPCGANGRCRSREGGYTCECFEDFTGEHCEVDARSGRCANGVCKNGGTCVNLLIGGFHCVCPPGEYERPYCEVTTRSFPPQSFVTFRGLRQRFHFTISLTFATQERNGLLLYNGRFNEKHDFIALEIVDEQVQLTFSAGETTTTVAPKVPSGVSDGRWHSVQVQYYNKPNIGHLGLPHGPSGEKMAVVTVDDCDTTMAVRFGKDIGNYSCAAQGTQTGSKKSLDLTGPLLLGGVPNLPEDFPVHNRQFVGCMRNLSVDGKNVDMAGFIANNGTREGCAARRNFCDGRRCQNGGTCVNRWNMYLCECPLRFGGKNCEQAMPHPQLFSGESVVSWSDLNIIISVPWYLGLMFRTRKEDSVLMEATSGGPTSFRLQILNNYLQFEVSHGPSDVESVMLSGLRVTDGEWHHLLIELKNVKEDSEMKHLVTMTLDYGMDQNKADIGGMLPGLTVRSVVVGGASEDKVSVRRGFRGCMQGVRMGGTPTNVATLNMNNALKVRVKDGCDVDDPCTSSPCPPNSRCHDAWEDYSCVCDKGYLGINCVDACHLNPCENMGACVRSPGSPQGYVCECGPSHYGPYCENKLDLPCPRGWWGNPVCGPCHCAVSKGFDPDCNKTNGQCQCKENYYKLLAQDTCLPCDCFPHGSHSRTCDMATGQCACKPGVIGRQCNRCDNPFAEVTTLGCEVIYNGCPKAFEAGIWWPQTKFGQPAAVPCPKGSVGNAVRHCSGEKGWLPPELFNCTTISFVDLRAMNEKLSRNETQVDGARALQLVRALRSATQHTGTLFGNDVRTAYQLLGHVLQHESWQQGFDLAATQDADFHEDVIHSGSALLAPATRAAWEQIQRSEGGTAQLLRRLEGYFSNVARNVRRTYLRPFVIVTANMILAVDIFDKFNFTGARVPRFDTIHEEFPRELESSVSFPADFFRPPEEKEGPLLRPAGRRTTPQTTRPGPGTEREAPISRRRRHPDDAGQFAVALVIIYRTLGQLLPERYDPDRRSLRLPHRPIINTPMVSTLVYSEGAPLPRPLERPVLVEFALLEVEERTKPVCVFWNHSLAVGGTGGWSARGCELLSRNRTHVACQCSHTASFAVLMDISRRENGEVLPLKIVTYAAVSLSLAALLVAFVLLSLVRMLRSNLHSIHKHLAVALFLSQLVFVIGINQTENPFLCTVVAILLHYIYMSTFAWTLVESLHVYRMLTEVRNIDTGPMRFYYVVGWGIPAIVTGLAVGLDPQGYGNPDFCWLSLQDTLIWSFAGPIGAVIIINTVTSVLSAKVSCQRKHHYYGKKGIVSLLRTAFLLLLLISATWLLGLLAVNRDALSFHYLFAIFSGLQGPFVLLFHCVLNQEVRKHLKGVLGGRKLHLEDSATTRATLLTRSLNCNTTFGDGPDMLRTDLGESTASLDSIVRDEGIQKLGVSSGLVRGSHGEPDASLMPRSCKDPPGHDSDSDSELSLDEQSSSYASSHSSDSEDDGVGAEEKWDPARGAVHSTPKGDAVANHVPAGWPDQSLAESDSEDPSGKPRLKVETKVSVELHREEQGSHRGEYPPDQESGGAARLASSQPPEQRKGILKNKVTYPPPLTLTEQTLKGRLREKLADCEQSPTSSRTSSLGSGGPDCAITVKSPGREPGRDHLNGVAMNVRTGSAQADGSDSEKP
# >1496 [organism=Human] [UniprotID=Q8N729] neuropeptide W-30
# WYKHVASPRYHTVGRAAGLLMGLRRSPYLW

#在页面找到蛋白质序列值
for i in range(len(HumanSwissProt)):
    uniprotUrl = 'https://rest.uniprot.org/uniprotkb/'+str(HumanSwissProt[i])
    response = requests.get(uniprotUrl)
    sequeceValue = response.json()['sequence']['value']
    targetId = str(TargetId[i])
    sequeceName = str(RGDName[i])

    content = '>'+targetId+' [organism=Human] [UniprotID='+str(HumanSwissProt[i])+'] '+sequeceName+'\n'+\
              sequeceValue+'\n'+\
              '>1496 [organism=Human] [UniprotID=Q8N729] neuropeptide W-30' \
              'WYKHVASPRYHTVGRAAGLLMGLRRSPYLW'

    sha = hashlib.sha1(content.encode('utf-8'))
    encryptsContent = sha.hexdigest()

    fileName = './sequeceResult/'+encryptsContent+'-'+str(HumanSwissProt[i])+'.'+'fasta'

    with open(fileName, 'w') as file:
        file.write(content)

        file.close()